- name: Using variables
  hosts: web
  vars: 
    name: Renuka
    course: ansible
  tasks:
  - name: print the information
    ansible.builtin.debug:
    msg: "Hi, I am {{name}} and I am learning {{course}}"
