- name: variables to print
  hosts: web
  
  tasks:
  - name: print the information
    vars:
      name: Renu
      #course: "DevOps with AWS from TASK level"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{course}}"

#1. command line/args
#2. Task level
#3. Files
#4. prompt
#5. Play
#6. inventory
#7. Roles